entry:
  entry_name: '...-Daq qaDor.'
  slug: '...-Daq_qaDor_sen'
  part_of_speech: sen:bc,tmpl
  pos: sen
  pos_subtype: bc
  categories:
  - tmpl
  status: canonical
  section: examples
  definition: I will escort you to ... .
  see_also: '{Dor:v:1}'
  notes: 'To answer in the affirmative, say {luq:excl} "okay".


    To answer in the negative, say {Qo'':excl} "no, I refuse".'
  components: '{-Daq:n:suff}, {qa-:v:pref}, {Dor:v:1}'
  examples: '

    ▶ {pa''lIjDaq qaDor.:sen:nolink} "I will escort you to your quarters."

    ▶ {tachDaq qaDor.:sen:nolink} "I will escort you to the bar."

    ▶ {vaS''a''Daq qaDor.:sen:nolink} "I will escort you to the Great Hall."'
  translations:
    de:
      definition: Ich begleite dich zum ... .
    fa:
      definition: من تو را به ... اسکورت می‌کنم ...
    sv:
      definition: Jag kommer eskortera dig till ....
    ru:
      definition: Я провожу тебя до ... .
    zh_HK:
      definition: 我送你去……。
    pt:
      definition: Eu escoltarei você para ....
    fi:
      definition: Saatan sinut ...:lle.
      notes: 'Jos haluat vastata myöntävästi, sano {luq:excl} "ok".


        Jos haluat vastata kieltävästi, sano {Qo'':excl} "ei, kieltäydyn".'
    fr:
      definition: Je vous accompagnerai jusqu'à... .
  _original_id: 16353
  _original_file: mem-28-examples.xml
