entry:
  entry_name: '... puS'
  slug: '..._puS_sen'
  part_of_speech: sen:alt,noanki,nodict
  pos: sen
  metadata_tags:
  - alt
  - noanki
  - nodict
  status: canonical
  nodict: true
  section: main
  definition: '{... X law'' ... X puS:sen}'
  components: '{puS:v:1}'
  sources:
    raw: '[1] {TKD:src}'
    citations:
    - source: tkd
  translations:
    de:
      definition: '{... X law'' ... X puS:sen}'
    fa:
      definition: '{... X law'' ... X puS:sen}'
    sv:
      definition: '{... X law'' ... X puS:sen}'
    ru:
      definition: '{... X law'' ... X puS:sen}'
    zh_HK:
      definition: '{... X law'' ... X puS:sen}'
    pt:
      definition: '{... X law'' ... X puS:sen}'
    fi:
      definition: '{... X law'' ... X puS:sen}'
    fr:
      definition: '{... X law'' ... X puS:sen}'
  _original_id: 12988
  _original_file: mem-11-p.xml
