entry:
  entry_name: Dev
  slug: Dev_v
  part_of_speech: v:t_c,klcp1
  pos: v
  pos_subtype: t_c
  metadata_tags:
  - klcp1
  status: canonical
  section: main
  definition:
    text: lead, guide
    parts:
    - text: lead
    - text: guide
  see_also: '{che'':v}, {DevwI'':n}'
  examples: '

    ▶ {juDev ''ej Dujvam ra''wI'' DagheS ''e'' vItlhob.:sen}'
  sources:
    raw: '[1] {TKD:src}'
    citations:
    - source: tkd
  translations:
    de:
      definition: leiten, führen
    fa:
      definition: سرب، راهنمای
    sv:
      definition: leda, guida
    ru:
      definition: вести, руководить
    zh_HK:
      definition: 領導、指導
    pt:
      definition: guiar, conduzir
    fi:
      definition: johtaa, opastaa
    fr:
      definition: diriger, guider [AUTOTRANSLATED]
  _original_id: 10646
  _original_file: mem-03-D.xml
