name: generate_db

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate_db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Perl dependencies
      uses: perl-actions/install-with-cpanm@stable
      with:
        cpanfile: "cpanfile"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate database
      run: |
        chmod +x ./generate_db.sh
        ./generate_db.sh --noninteractive
